version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=who_cares_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: